# Generated by Django 5.2.7 on 2025-10-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"verbose_name": "部门管理", "verbose_name_plural": "部门管理"},
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="公司名称"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(max_length=64, verbose_name="部门名称"),
        ),
    ]
