# Generated by Django 5.2.7 on 2025-10-18 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_alter_department_options_user_company_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, verbose_name="用户名")),
                ("ip", models.GenericIPAddressField(verbose_name="登录IP")),
                (
                    "status",
                    models.CharField(
                        choices=[("成功", "成功"), ("失败", "失败")],
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="时间")),
            ],
            options={
                "verbose_name": "登录日志",
                "verbose_name_plural": "登录日志",
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=100, verbose_name="系统模块")),
                ("operator", models.CharField(max_length=50, verbose_name="操作人员")),
                ("ip", models.GenericIPAddressField(verbose_name="操作IP")),
                ("action", models.CharField(max_length=100, verbose_name="操作内容")),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="时间")),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "启用"), (0, "停用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="岗位名称")),
                ("code", models.CharField(max_length=50, verbose_name="岗位编码")),
            ],
            options={
                "verbose_name": "岗位管理",
                "verbose_name_plural": "岗位管理",
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "启用"), (0, "停用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="工具名称")),
                ("api_url", models.URLField(verbose_name="API接口地址")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="说明"),
                ),
            ],
            options={
                "verbose_name": "检测工具管理",
                "verbose_name_plural": "检测工具管理",
            },
        ),
        migrations.CreateModel(
            name="WorkflowConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "启用"), (0, "停用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="流程名称")),
                ("steps", models.TextField(verbose_name="流程步骤（JSON）")),
            ],
            options={
                "verbose_name": "审批流程配置",
                "verbose_name_plural": "审批流程配置",
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "启用"), (0, "停用")],
                        default=1,
                        verbose_name="状态",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="菜单名称")),
                ("path", models.CharField(max_length=200, verbose_name="路径")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="system.menu",
                        verbose_name="上级菜单",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜单管理",
                "verbose_name_plural": "菜单管理",
            },
        ),
    ]
