# Generated by Django 5.2.7 on 2025-10-15 13:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("os", models.CharField(max_length=50, verbose_name="操作系统")),
                ("middleware", models.CharField(max_length=100, verbose_name="中间件")),
                (
                    "jdk_version",
                    models.CharField(max_length=50, verbose_name="JDK版本"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusinessDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="业务部门")),
            ],
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="组件名称")),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="项目名称")),
                (
                    "project_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="项目ID",
                    ),
                ),
                (
                    "final_user",
                    models.CharField(max_length=200, verbose_name="最终用户"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="项目描述"),
                ),
                (
                    "expected_launch",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="预计上线时间"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("in_progress", "进行中"),
                            ("pause", "暂停"),
                            ("completed", "已完成"),
                            ("closed", "关闭"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "base_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.baseimage",
                        verbose_name="基础镜像版本",
                    ),
                ),
                (
                    "business_department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="projects.businessdepartment",
                        verbose_name="业务部门",
                    ),
                ),
                (
                    "components",
                    models.ManyToManyField(
                        blank=True, to="projects.component", verbose_name="其他组件"
                    ),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目管理",
            },
        ),
    ]
