# Generated by Django 5.2.7 on 2025-10-15 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("system", "0002_alter_department_options_user_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="business_department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="system.department",
                verbose_name="业务部门",
            ),
        ),
    ]
