# Generated by Django 5.2.7 on 2025-10-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_project_business_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="base_image",
            field=models.CharField(
                choices=[
                    ("draft", "草稿"),
                    ("in_progress", "进行中"),
                    ("pause", "暂停"),
                    ("completed", "已完成"),
                    ("closed", "关闭"),
                ],
                default="draft",
                max_length=20,
                null=True,
                verbose_name="基础镜像版本",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("system", "操作系统"),
                    ("middle", "中间件"),
                    ("jdk", "JDK版本"),
                ],
                default="system",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
