# Generated by Django 5.2.7 on 2025-10-18 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="镜像名称")),
                ("version", models.CharField(max_length=50, verbose_name="镜像版本号")),
                (
                    "image_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="镜像ID"
                    ),
                ),
                ("size", models.CharField(max_length=50, verbose_name="镜像大小")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "基础镜像组件",
                "verbose_name_plural": "基础镜像组件",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BusinessImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="镜像名称")),
                ("version", models.CharField(max_length=50, verbose_name="镜像版本号")),
                (
                    "image_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="镜像ID"
                    ),
                ),
                ("size", models.CharField(max_length=50, verbose_name="镜像大小")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "业务镜像",
                "verbose_name_plural": "业务镜像",
                "ordering": ["-created_at"],
            },
        ),
    ]
